# Force UTF-8 encoding
encoding: utf-8

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-redirect-from

remote_theme: ritovision/owasp-sitetheme@fix-mobile-layout-urlpatch

include:
  - .well-known

defaults:
  - scope:
      path: "pages/events/featured"
    values:
      event: true

# Force fresh builds
sass:
  cache: false
  style: compressed