remote_theme: ritovision/owasp-sitetheme@fix/broken-mobile-layout
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-redirect-from
include:
  - .well-known
defaults:
  - scope:
      path: "pages/events/featured"
    values:
      event: true

# If your repo is named owasp.github.io:
baseurl: "/owasp.github.io"
url: "https://ritovision.github.io"